### ISSUE TITLE
credentials for web interface

### ISSUE THREAD

**Issue by digitalbanana** [fss/solis-inverter#17]
Hi There,
Any advice on what to use as the username/password - or where to find them please?
I have looked through the inverter device ui but cant see where this is set anywhere.

Any help greatly appreciated

Dave

**Comment by fss** [comment]
so you say you can access your inverter's web interface without logging in?

**Comment by digitalbanana** [comment]
Hi Rafael, tha KS for the response. No, sorry if not clear, I can't access the web interface via the inverter up address using either a browser or this app. I get a 401 unauthorized response.

Have tried:
admin/admin
admin/123456789

But neither work, not sure what to try or where to search for suggestions....

Thank you

**Comment by fss** [comment]
well, for me default one was admin/admin. but I don't think this is the best place to ask this question, tho ;) I advice you to look on Ginlong support sites / forums :) good luck!

**Comment by digitalbanana** [comment]
if anyone comes across this - i manged to find [this page](https://github.com/hn/ginlong-solis) which states the following:

> The web interface is protected by HTTP simple auth with fixed username admin and password 123456789. After connecting the stick to your home WiFi the web password changes without notice to your WiFi password. So you need to login to the web admin interface with admin and your WiFi password. This somewhat wierd behaviour again shows the immature state of the firmware.

this worked for me 👍
