### ISSUE TITLE
Port=8000

### ISSUE THREAD

**Issue by Oskar70** [fss/solis-inverter#23]
I tried your code and get no errors but also no results. It might be the port number. In your code you use 8000. Can you give me a hint how to get the correct code? I have a Solis 4G inverter and I can acces the Wifi Dongle via IP as in screenshot. Hope you can help.
![ScreenshotWiFiDongleIP192 168 222 31](https://github.com/fss/solis-inverter/assets/124258121/c2cee6dd-6da9-4b41-99d9-509905134fa9)

**Comment by fss** [comment]
can you paste your logs output?

**Comment by Oskar70** [comment]
Hello Rafal, thanks for offering help. I gave up implementing  any direct link to the ginlong wifi dongle and purchased a Shelly 3em instead (65€ + little money for elctrician). Should have done that much earlier.--Gesendet mit der WEB.DE Mail AppAm 08.07.24, 21:35 schrieb Rafal Drag ***@***.***>:

   
  can you paste your logs output?
