### ISSUE TITLE
Address not given

### ISSUE THREAD

**Issue by luisgarcia87** [fss/solis-inverter#3]
Hi! I am trying to use your script but I get the error Address not given. Here is my command:

node index.js --address 192.168.1.48 --username admin --password admin --port 10000

Do you have an idea of what might be happening?

This is my inverter 

Firmware version (main)003A
Firmware version (slave)001B
Inverter model00B

**Comment by fss** [comment]
ah sorry I forgot to update README, syntax is changed now:

`SOLIS_ADDRESS=192.168.1.48 SOLIS_USERNAME=admin SOLIS_PASSWORD=admin node index.js `

port 8000 is exposed

**Comment by fss** [comment]
you can also try the dockerised version, available here:
https://hub.docker.com/r/stryjek4/solis-api

**Comment by luisgarcia87** [comment]
Thank you! I got it working now.

Can you tell me how do you make it start at boot? 

I tried using forever-service but the status of the service show this:

> Nov 06 22:28:28 raspberrypi systemd[1]: Starting LSB: forever-service startup script for solis-inverter...
Nov 06 22:28:29 raspberrypi solis-inverter[15513]: (node:15515) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
Nov 06 22:28:29 raspberrypi solis-inverter[15513]: (Use `node --trace-warnings ...` to show where the warning was created)
Nov 06 22:28:29 raspberrypi solis-inverter[15513]: (node:15515) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
Nov 06 22:28:30 raspberrypi solis-inverter[15513]: Starting solis-inverter
Nov 06 22:28:31 raspberrypi solis-inverter[15513]: (node:15527) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
Nov 06 22:28:31 raspberrypi solis-inverter[15513]: (Use `node --trace-warnings ...` to show where the warning was created)
Nov 06 22:28:31 raspberrypi solis-inverter[15513]: (node:15527) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
Nov 06 22:28:31 raspberrypi systemd[1]: Started LSB: forever-service startup script for solis-inverter.

**Comment by fss** [comment]
I guess you need to pass `--workingDir     The working directory in which SCRIPT will execute` parameter to forever daemon.

**Comment by luisgarcia87** [comment]
I found an easy way for it to start at boot.

I created a bash script in **/home/pi/solis-inverter-start-at-booth.sh**:
`#!/bin/bash
cd /home/pi/solis-inverter-master
sudo SOLIS_ADDRESS=192.168.1.48 SOLIS_USERNAME=admin SOLIS_PASSWORD=admin node index.j`

_Remember to change 192.168.1.48 with your Inverter IP Address and SOLIS_USERNAME and SOLIS_PASSWORD with the corresponding credentials of your inverter._

After creating the script I edited the rc.local file with the command **sudo nano /etc/rc.local** and I added this line before the exit 0:
`sudo bash /home/pi/solis-inverter-start-at-boot.sh &`

And know the script starts at boot.

Thanks for your help @fss

**Comment by fss** [comment]
good to know it's working fine :)
