### ISSUE TITLE
JSON output to Home Assistant

### ISSUE THREAD

**Issue by luisgarcia87** [fss/solis-inverter#4]
Hi, I just want to see if anyone knows how to integrate the solis-inverter output to Home Assistant, to be able to read it's values. I have the following json output:

``{"lastSeen":1605035609563,"inverter":{"model":"00B7",,"firmwareMain":"003A","firmwareSlave":"001B"},"logger":{,"version":"MW_08_512_0501_1.80","mode":"STA","ap":{"ssid":"AP_724118333","ip":"10.10.100.254",},"sta":{"ssid":"Home","ip":"192.168.1.48","rssi":"42%"}},"remoteServer":{"a":true,"b":false},"power":2626,"energy":{"today":32,"total":647}}``

But I don't know how I can make a sensor in Home Assistant that would read for instance the "power" value.

Any help it's appreciated.

Thanks

**Comment by fss** [comment]
For this topic I'd recommend you ask on HomeAssistant forums, as this API is platform agnostic and I created it for use with OpenHAB, not HomeAssistant. I can imagine though creating a simple HTTP binding with equally simple JSON parser that would feed the sensor.

Good luck!

**Comment by luisgarcia87** [comment]
I managed to added to Home Assistant, to anyone interested just add the following line to your configuration.yaml file

`  sensor:
      - platform: rest
        name: Solis power 
        resource: http://IP_TO_THE_REST_API
        value_template:  '{{ value_json.power }}'`

**Comment by fss** [comment]
good to know!
