### ISSUE TITLE
Refresh Interval not working

### ISSUE THREAD

**Issue by luisgarcia87** [fss/solis-inverter#8]
Hi! can you tell me if it works for you to set the interval to something else rather than the 30 seconds default? I could not get it to work using the INTERVAL command, also my solis is updating it's values every 60 seconds and not the 30 seconds default option, does someone have any clue of why this is happening?

**Comment by fss** [comment]
just checked the native node.js call:

`s4@s4-mbp solis-inverter % INTERVAL=60 node index.js 
{ interval: 60 }`

**Comment by luisgarcia87** [comment]
how would I input the command in order to get... say a refresh every 5 seconds?

**Comment by fss** [comment]
30 is a minimum, as I checked the HTTP interface tended to be lagging and acting unstable if refreshed too frequent. hence the lower limit.

for fetching the data more often I'd rather suggest using modbus module

**Comment by luisgarcia87** [comment]
Ok i get it now thanks for clearing it up.
